### ISSUE TITLE
Coal mine image not showing on cloudinary urls article

### ISSUE THREAD

**Issue by growdigital** [leviwheatcroft/metalsmith-all-the-things#1]
The coal mine image at the bottom of the article isn't displaying

https://github.com/leviwheatcroft/metalsmith-all-the-things/blob/master/src/articles/cloudinary-urls.md

**Comment by leviwheatcroft** [comment]
You mean when you view it on github? Or when you build & serve locally?

For the image to be displayed correctly, the `marked-cloudinary` renderer needs to be plugged in when transpiling md to html. Github will use it's own engine to render the md shown on github, which of course doesn't use `marked-cloudinary`.

I put a note about this on that page.

**Comment by growdigital** [comment]
Ahh, I mean on github! Didn't realise it was meant to be viewed on your own environment!
